Add 'Django_5_by_Example' to the 'django" folder and  'Python_Cheat_Sheet' to the 'cheat-sheets" folder
mr-mib/Open-Source-Engineering-Books pull request #8
Opened 2024-06-19 08:38 UTC by sibylassana95

2024-06-19 22:02 UTC, mr-mib commented on books/django/Django_5_by_Example.pdf
Good evening.
as recommended, you should have dash between word instead of underscore.
In addition, every single word should _**start**_ with a **capital letter**

2024-06-19 22:02 UTC, mr-mib requested changes
Good evening.
as recommended, you should have dash between word instead of underscore.
In addition, every single word should start with a capital letter

2024-06-19 22:03 UTC, mr-mib requested changes
Good evening.
as recommended, you should have **dash** between word instead of underscore.

2024-06-19 22:04 UTC, mr-mib requested changes
Good evening.
as recommended, you should have **dash** between word instead of underscore.
In addition, every single word should **_start_** with a **capital letter**

2024-06-20 08:36 UTC, sibylassana95 commented on books/django/Django_5_by_Example.pdf
hello, c'est fait

2024-06-20 10:20 UTC, mr-mib commented on books/django/Django_5_by_Example.pdf
super

2024-06-20 10:20 UTC, mr-mib approved these changes
well done!

2024-06-20 18:00 UTC, merged